### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by wont-stream** [vincentneo/LosslessSwitcher#145]
Hi, I absolutely know that this is the wrong place to ask, but I was wondering if anyone has come across something like this for Windows? I’ve searched across GitHub and Reddit, but haven’t found anything.

Thanks

**Comment by vyconm** [comment]
I think your best bet is to look at a palyer that does this that is compatible with your input media of choice, most players on Windows switch sample rates and bit depths already (it is much easier to do and implement there, but also less stable overall - I used to hate producing music on windows because of all the asio stuff, but it is very flexible)

AFAIK, nothing like this exists for Apple Music on Windows - isn't that also still in beta?


Maybe look for some flac specific players made for audiophiles, they might have that feature :)

**Comment by wont-stream** [comment]
I believe it is still in beta yeah, and I'll definitely check out some audiophile media players, hadn't thought about that.

Thanks!

**Comment by MasterRahool** [comment]
> I believe it is still in beta yeah, and I'll definitely check out some audiophile media players, hadn't thought about that.

been out of beta 6 months ago fwiw, not that it's any better

also, my frustration with Apple Music has got me migrating over to Plex / PlexAmp lately, maybe worth checking out (on Windows, though I use it on both now). I know it has exclusive mode on desktop but I havent really tested it out yet since I mostly stream to another device.
